export default (app) => {
  app.post(
    `/tenant/:tenantId/country`,
    require('./countryCreate').default,
  );
  app.put(
    `/tenant/:tenantId/country/:id`,
    require('./countryUpdate').default,
  );
  app.post(
    `/tenant/:tenantId/country/import`,
    require('./countryImport').default,
  );
  app.delete(
    `/tenant/:tenantId/country`,
    require('./countryDestroy').default,
  );
  app.get(
    `/tenant/:tenantId/country/autocomplete`,
    require('./countryAutocomplete').default,
  );
  app.get(
    `/tenant/:tenantId/country`,
    require('./countryList').default,
  );
  app.get(
    `/tenant/:tenantId/country/:id`,
    require('./countryFind').default,
  );
};
